# cloudbuild.yaml test commit for trigger!

steps:
  # STEP 2: Build the application. This step ALSO needs to use the cache.
  - name: 'maven:3.8.5-openjdk-17'
    id: 'Build Application'
    entrypoint: 'mvn'
    args: ['package', '-DskipTests']
    #wait_for: ['Run Tests']
    # THIS IS THE FIX: Add the volumes block here as well.
    volumes:
      - name: 'm2-cache'
        path: '/root/.m2'

 # STEP 3: Build the production container image.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Container Image'
    # Use the correct repository name: "gorilla-clinic-images"
    args: ['build', '-t', '$_REGION-docker.pkg.dev/$_PROJECT_ID_TO_DEPLOY_TO/gorilla-clinic-images/$_SERVICE_NAME:$COMMIT_SHA', '.']
    wait_for: ['Build Application']
    volumes:
      - name: 'm2-cache'
        path: '/root/.m2'

  # STEP 4: Push the container image to Artifact Registry.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Container Image'
    # Use the correct repository name: "gorilla-clinic-images"
    args: ['push', '$_REGION-docker.pkg.dev/$_PROJECT_ID_TO_DEPLOY_TO/gorilla-clinic-images/$_SERVICE_NAME:$COMMIT_SHA']
    wait_for: ['Build Container Image']

 # =========================================================
  # STEP 4: DEPLOY TO EUROPE-WEST4
  # =========================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to europe-west4'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      # Target the specific regional service name
      - 'gorilla-clinic-europe-west4'
      - '--image=europe-west4-docker.pkg.dev/$_PROJECT_ID_TO_DEPLOY_TO/gorilla-clinic-images/gorilla-clinic:$COMMIT_SHA'
      - '--region=europe-west4'
      - '--project=$_PROJECT_ID_TO_DEPLOY_TO'
      - '--service-account=gorilla-clinic-sa@$_PROJECT_ID_TO_DEPLOY_TO.iam.gserviceaccount.com'
    wait_for: ['Push Container Image']

  # =========================================================
  # STEP 5: DEPLOY TO US-CENTRAL1
  # =========================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to us-central1'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      # Target the specific regional service name
      - 'gorilla-clinic-us-central1'
      - '--image=europe-west4-docker.pkg.dev/$_PROJECT_ID_TO_DEPLOY_TO/gorilla-clinic-images/gorilla-clinic:$COMMIT_SHA'
      - '--region=us-central1'
      - '--project=$_PROJECT_ID_TO_DEPLOY_TO'
      - '--service-account=gorilla-clinic-sa@$_PROJECT_ID_TO_DEPLOY_TO.iam.gserviceaccount.com'
    wait_for: ['Push Container Image']

# Make the newly pushed image available for the deploy step
images:
  - '$_REGION-docker.pkg.dev/$_PROJECT_ID_TO_DEPLOY_TO/gorilla-clinic-images/$_SERVICE_NAME:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY